buildit/buildit

- src/careers.html
- src/components/buildit.css
- src/contact.html
- src/index.html
- src/make.html
- src/values.html
Fixing css imports in html pages.
Requiring css modules in the main css stylesheet (buildit.css).
> fix 15 css imports

- README.md
- gulpfile.js
- package.json
- src/components/buildit.css
- src/components/header.css
- src/index.html
Added gulp integration, with browsersync and watch
> Homepage update

- gulpfile.js
- package.json
- src/buildit.html
- src/careers.html
- src/components/buildit.css
- src/contact.html
- src/index.html
- src/js/index.js
- src/make.html
- src/values.html
Simplify the build file and packages. @FiF0o
> Gulp build

- gulpfile.js
- package.json
> Live reload

- gulpfile.js
- package.json
Open localhost:8080 in default browser.
> Open browser

- src/components/contact-details-buildit.css
- src/components/contacts-buildit.css
- src/contact5.html
should be the page locked down based on various peers feedback
> add concept5 contact page

- gulpfile.js
- package.json
Add source maps and fix minification of CSS.
> Css sourcemap

- src/about.html
- src/index.html
- src/people.html
Added text from Urmy: https://paper.dropbox.com/doc/Buildit.digital.com-78rQi33Efs9z2PfhIJtHg
Layout is basic and there are some formatting issues on `<ul>`s (smaller font than paragraph text).
> Bw new dev jamesnash

- src/components/contacts-buildit.css
- src/components/site.css
- src/contact.html
* Updates the colours and font sizes
* Adjust general sizing
* Includes map markers
* Moved link for location to map marker rather than text
* *Updates global font-weight of the h1*(!)
> Contact page updates

- src/about.pug
Spacing fix between some words in about page.
> Spacing fix

- gulpfile.js
- package-lock.json
- package.json
- pipelines/production.groovy
- pipelines/staging.groovy
- src/index.pug
Just mimicked the current deployment mechanism. Next step would be to use images.
> Initial pipelines work

- src/about.pug
- src/includes/footer.pug
- src/make.pug
This PR changes http to https links to keep it consistent and demonstrate our preference to https.
> Modify http links to https wherever supported

- src/components/main.css
- src/contact.pug
- src/less/contact.less
- src/less/main.less
Main change is the new address. And, yes, the lowercase "ul." is indeed correct!
Also, it's long bothered me that there was no space between the bottom row of address cards and the page footer, so I took this opportunity to rectify that.
> Added Polish office address (and made contact page less fugly)

- .travis.yml
- scripts/notify.sh
The script was being interpreted incorrectly by travis so the statement has been removed and placed in a script file so it is handled correctly and at the right phase
> Fixing a scripting issue on the travis build file.

- .travis.yml
- scripts/notify.sh
Updates to read variable directly from session as passing them in doesn't work consistently throughout script tags
> Updates to read variable directly from session

- package-lock.json
- package.json
This Gravity update brings across a few CSS fixes, including the text alignment on job listings (WEB-174).
> Upgraded Gravity dependency to 0.6.1

- templates/partials/molecule-job-card.hbs
Removes full time mention from job titles
> Removed job type / full time

- templates/partials/page-footer.hbs
Fixes footer linkedin link that was going to a wrong company
> Web 190 linkedin link on footer

- src/sass/style.scss
> WEB-193 - location cards fix

- .pa11yci.json
- .travis.yml
- cypress.json
- cypress/integration/smoothScroll_spec.js
- docs/tests.md
- package.json
- Add tests for the following pages: homepage, about, careers, locations.
- Add commands for the following features: scroll reveal, smooth scroll, toggle menu.
> Web 146 accessibility

- pages/index.md
- src/sass/style.scss
- templates/homepage.hbs
Screenshots with different backgrounds attached in commit
> WEB-205 - Replaced company logos with industries

- package-lock.json
- package.json
- templates/partials/page-footer.hbs
* Upgraded to new Gravity release
* Updated footer icons to new IDs
* Added Github link to footer
> Upgrade to Gravity 0.8.0

- pages/index.md
- templates/about.hbs
Minor changes requested by Oli:
* Moved 'systems thinking' to bottom of passion list.
* Added 'digital' to hero tagline.
> WEB-231 & WEB-232: Copy tweaks

- src/sass/_flourish-groups.scss
- src/sass/_flourish.scss
- src/scripts/scrollReveal/scrollRevealModule.js
Minor layout changes improving the look and feel of the transparent header.
> Tweak flourishes

- package-lock.json
- package.json
- pages/index.md
- templates/homepage.hbs
- templates/partials/page-header.hbs
Also made the Buildit logo on the homepage the H1 (since there was none so far) as this is now supported by Gravity 0.9.1
> Upgrade to Gravity 0.9.1

- src/scripts/heroAnimation/hero.js
> fixes #WEB-230 - focus/initial animation position for dots on mobile

- src/scripts/smoothScroll/scrollModule.js
Changes animation default settings
> WEB-198 scroll easing

- pages/locations/bengaluru.md
- pages/locations/denver.md
- pages/locations/dublin.md
- pages/locations/edinburgh.md
- pages/locations/london.md
- pages/locations/new-york.md
Amends coordinates for static maps. 
See pages >  locations
> WEB-235 Google maps locations are not accurate

- CHANGELOG.md
- pages/locations/edinburgh.md
- pages/locations/gdansk.md
- pages/locations/london.md
> Change TLD to .com

- CHANGELOG.md
- templates/partials/scripts-footer.hbs
This change will help us with the GDPR thing.
https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization
> Adds ip anonymisation to GA

- CHANGELOG.md
- package-lock.json
- src/scripts/heroAnimation/__tests__/utils.test.js
- src/scripts/heroAnimation/utils.js
https://digitalrig.atlassian.net/browse/WEB-261
> Fixing Math.hypot fallback for IE

- package-lock.json
- templates/partials/page-footer.hbs
This one adds a link to the footer that will bring the user to the official wipro digital privacy policy.
> Adds privacy policy to footer

- CHANGELOG.md
- pages/locations/dallas.md
> Added Dallas office to locations page

- gulpfile.js
- package-lock.json
- pages/locations/warsaw.md
* Updates the Warsaw studio address and map
* Fixes a build error introduced by a recent dependency update (that only manifested itself on production builds - hence why it was missed before)
> Warsaw address update

- pages/locations/denver.md
- templates/partials/molecule-location-card.hbs
The Denver studio is moving. This updates their address on the locations page.
> Updates Denver studio address (WEB-276)

- package.json
- pages/locations/denver.md
- pages/locations/plano.md
- templates/partials/molecule-location-card.hbs
Releases recently merged PR - in particular an update to the Denver studio address as they are moving tomorrow.
> Release: Denver fix

- src/sass/style.scss
- src/scripts/heroAnimation/hero.js
Fixes 2 rather embarrassing bugs:
* The hamburger menu button on the homepage is broken (on small-screened, touch devices)
* The Buildit logo has some unwanted margin above it on small viewports
> Header fixes

- docs/build-process.md
- docs/coding-standards.md
- gulp/gravity-assets.js
- package-lock.json
- package.json
- src/sass/style.scss
Updates the website to `@buildit/gravity-ui-web`, version 1.0.0. :-)
> Gravity update

- src/sass/_banner.scss
- src/sass/_flourish.scss
- src/sass/style.scss
- templates/partials/organisms-list-img-cards.hbs
Very much dependent on https://github.com/buildit/gravity-ui-web/pull/220 going through.
> feat: dark mode

- .travis.yml
- package-lock.json
- package.json
- src/sass/_banner.scss
- src/sass/_flourish.scss
- src/sass/style.scss
- templates/partials/organisms-list-img-cards.hbs
Releases recent PRs.
Most notably:
* Dark mode (built on Gravity 2.0)
* Fixes broken CloudFront cache invalidation
> Release the dark side

- layouts/default/footer.njk
- layouts/partials/blocks/footer.njk
- package-lock.json
I took the liberty to update the footer code within the website to match the code for the updated Gravity page-footer component.
This will allow us to show off @ashblue 's good work 👍 
I've used the header collection as a basis for the left column of links and the right column don't have pages to go to yet so they're just `#` links
> feat(footer): updated footer markup to match gravity component

- config/envs.json
- gulpfile.js
- layouts/default/header.njk
- layouts/partials/head.njk
Adds Gravity's `debug.css` to local dev builds. This can help spot mark-up issues that can interfere with Gravity's styling.
> Adds Gravity debug.css

- layouts/default/header.njk
Current organisation data is showing an error in googles structured data tool
> refactor(structured data): used full url for Organization data

- layouts/partials/articles/list-item.njk
- package-lock.json
- package.json
- pages/jobs/index.html.njk
- src/sass/style.scss
Bumps to the latest Gravity NEXT pre-release, which introduces new and updated multi-column layout
classes. This change also updates some of the website templates' mark-up to use those new classes
correctly.
> refactor: updates to latest Gravity release

- layouts/default/footer.njk
As per our call, updated the footer contents to reflect the Wipro Digital copyright and removed the redundant links.
> refactor(footer content): updated the copyright and footer links

- metalsmith.js
Small update to order the locations collection.
> refactor(locations): sort locations by title

- pages/locations/warsaw.md
Updated location of Warsaw office:
* Moved pin to the new office location
* Added img to match the location
> Updated location of Warsaw's office

- README.md
- package-lock.json
- package.json
- pages/about.md
- pages/careers.md
- pages/humans.txt
- pages/index.md
- pages/locations.md
- src/sass/style.scss
- templates/about.hbs
- templates/careers.hbs
- templates/partials/molecule-location-card.hbs
- templates/partials/page-footer.hbs
- templates/partials/page-header.hbs
Updates "old" site with Buildit 2.0 logo and tweaks to the wording to tide us over until the new (`next`) website is ready.
> Interim updates
