buildit/buildit

- src/about.html
- src/asyncgrid.html
- src/contact-details.html
- src/contact.html
- src/index.html
- src/layout.html
- src/make.html
- src/nestedgrid.html
- src/people.html
- src/values.html
I ran our pages through the W3C validator and it picked up some _very_ minor issues. Being the OCD markup nut that I am, I couldn't resist fixing them! :-P
The issues were:
* Missing lang attribute on some pages
* Invalid `chrome=1` content on `X-UA-Compatible` meta-tag. This is a legacy thing for the Chrome frame plug-in for IE6 - 9. I think we no longer need to worry about that 2017 :-)
* Iffy HTML comment syntax on people page
I also simplified the viewport meta-tag by removing the redundant decimal point on `initial-scale`
> Fixed HTMl validator errors and warnings.

- src/contact.pug
This PR:
* modifies geolocation of bangalore studio accurately to [an existing place of parent company](https://www.google.com/maps/place/Wipro+Limited/@12.838566,77.6592042,16z/data=!4m5!3m4!1s0x0:0x1d0caf77fe02554f!8m2!3d12.8384852!4d77.6571581?hl=en-US)
* adds attribute `rel` to use [best practice](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md) for opening external links
> Improve geolocation for bangalore studio

- src/contact.pug
An earlier PR introduced an address error. This PR fixes the one word error in address of bangalore studio.
> Correct address of bangalore studio

- src/js/index.js
Appending this ID allows us to associate job applications with the Buildit website in SmartRecruiter's analytics, so we can see exactly how many people found our job ads via our website rather than some other source.
> WEB-93: Added SmartRecruiters tracking ID to job ad links.

- CHANGELOG.md
- gulp/gravity-assets.js
- gulp/metalsmith.js
- package-lock.json
- package.json
- templates/homepage.hbs
- templates/partials/page-footer.hbs
- templates/partials/page-header.hbs
- templates/partials/page.hbs
* Introduced `handlebars-layouts` helper (so you need to run `npm i`!) so that don't need to duplicate the HTML shell in each page template.
* Added static header & footer partials
* Note: We should be generating the nav links and also the footer links from data. We can raise a new story for that. I was just focussing on wiring it into the build here.
* Added inlining of the SVG sprites provided by Gravity (as these are needed for the buildit logo and social media icons that appear in header & footer)
* Added a CHANGELOG file too
> Added basic header & footer

- templates/about.hbs
- templates/homepage.hbs
I was getting some weird behaviour in Firefox where the hamburger toggle button didn't work. It turns out the click event handler was registered twice, so it got toggled and then toggled back again on a single click. On closer inspection, this was because some pages included all the `<script>` tags twice, so our init scripts were also being run twice.
This fixes that.
> Removed duplicate script includes.

- templates/about.hbs
Copy udpated on blog link. We could maybe split it in 2 hrefs for "continuous improvement" and "systems thinking" if it the link seems a bit long now?
> Web 167 change "organisational change" blog link on about us page

- .travis.yml
Just spotted a small bugs in our Travis config (probably due to a bad merge):
* The build step was occurring twice.
* Additionally, the 2nd build wasn't setting the correct site environment config, so it defaults to "locahost" which then causes the wrong `robots.txt` to be generated and deployed.
This PR fixes those issues.
> Fixed double build in Travis

- config.json
- gulp/metalsmith.js
- templates/partials/scripts-footer.hbs
This PR adds the JS calls needs for Google Analytics to work.
To prevent our GA stats from being polluted with data from local dev or testing on staging & beta envs, I have done the following:
* On local builds the GA scripts are omitted completely
* On beta and staging a newly created GA "property" is used (so we gets stats, but they are separate from the live site)
* On production is uses the existing Buildit website GA "property".
> Added GA script for beta, staging and production envs.

- gulp/metalsmith.js
- pages/about.md
- pages/careers.md
- pages/locations.md
- templates/partials/flourish.hbs
- templates/partials/page-header.hbs
- templates/partials/presentation-svg.hbs
- templates/partials/scripts-footer.hbs
Running our beta site through the W3C's validator was producing a number of errors and warnings. This PR fixes the _errors_ that originate from the website's code (some errors are due to the SVG symbols from Gravity - the ["SVG cleanup" PR](https://github.com/buildit/gravity-ui-sass/pull/91) will ensure the next Gravity release will fix those). Specifically, this PR fixes the following issues:
* Invalid `alt` on SVG
* Invalid `defer` on `<script type="module">`
* Duplicate `id`s on pages that use flourishes
* Invalid `gradientUnits` attribute on SVG `<path>` element
Note: There are still some validations _warnings_ due to unnecessary ARIA roles. These will require a change to Gravity's CSS though, so they are being left alone for now.
> HTML validation fixes

- src/sass/_flourish-groups.scss
Resolved issues WEB-248 & WEB-249.
**WEB-248:** White gap at bottoms of careers page.
**WEB-249:** Jagged scrolling on careers page.
In **flourish-groups** stylesheet - changed the transform rotate from **174 degrees** to **176 degrees** (for _polygon-shape-3a_), as it stops the boundary box for the flourish from overflowing from the footer (to outside the entire page's container).
> Mobile bugs: WEB-248/9 - tweaked flourish settings

- CHANGELOG.md
- templates/partials/scripts-footer.hbs
this improves a bit the performance of the pages where the actual bug is happening.
Should help underpin the big a bit better.
> refs #WEB-257 - removed CND scripts when not needed

- CHANGELOG.md
- pages/humans.txt
Matteo's role was incorrectly listed as "Metalsmithy" in our `humans.txt`. This grave error has now been fixed.
> Updated humans.txt

- CHANGELOG.md
- cypress/integration/about.js
- cypress/integration/careers.js
- cypress/integration/locations.js
- package-lock.json
- package.json
- pages/404.md
- pages/about.md
- pages/careers.md
- pages/index.md
- pages/locations.md
- src/sass/_banner.scss
- templates/partials/page-footer.hbs
- templates/partials/page-header.hbs
This Gravity release made the light header variant the default and removed the modifier class that was previously used to make the header appear light. It also changed the class name `grav-c-block-link` to `grav-c-nav-link`.
This PR therefore makes the necessary amendments to the website's templates and pages. It also removed a bunch of now-redundant CSS code from the website (which was previously overriding things that are now fixed or changed in Gravity's own CSS).
> Upgraded to Gravity v0.10.0

- CHANGELOG.md
- pages/locations/bengaluru.md
- pages/locations/denver.md
- pages/locations/dublin.md
- pages/locations/edinburgh.md
- pages/locations/gdansk.md
- pages/locations/london.md
- pages/locations/new-york.md
- pages/locations/warsaw.md
* Corrected Edinburgh address in Google Maps link (house number 2, not "32/2")
* Updated alt texts for all studios to be more descriptive
* Corrected marker coords for all static map images (they were previously using same coords as map link, however those coords are where the full map is centred, _not_ where the location pin appears!)
> Fixing map pins on locations page

- CHANGELOG.md
- config.json
- cypress/integration/homepage.js
- gulp/metalsmith.js
- templates/partials/page-footer.hbs
- templates/partials/page-header.hbs
Marketing have informed us that, when written as text, our name should be in title case: "Buildit @ Wipro Digital".
This PR corrects any instances where that was not already the case.
> Corrected capitalisation of "Buildit @ Wipro Digital" text

- CHANGELOG.md
- src/scripts/scrollReveal/scrollRevealModule.js
- templates/partials/scripts-footer.hbs
Adds scrollreveal into our JS bundle instead of being loaded separately via CDN.
In terms of performance, I estimate this won't really make any difference. We save one HTTP request, but our bundle's size increases. On balance, they probably cancel each other out.
However, this is still worth doing, since it makes it easier to stay up-to-date with new versions of scrollreveal since we can just do `npm update`.
> Bundle scrollreveal

- config.json
- gulp/metalsmith.js
- templates/partials/scripts-footer.hbs
google tag manager allows us to control any future analytics changes from a web based console.
tracking the smartrecruiters links allows us to measure our success as they are a primary call to
action
fix WEB-271
> feat(analytics): switch to GTM and track smart recruiters links

- pages/locations/plano.md
Renaming the "Dallas" entry on the locations page to "Plano", as requested by Ellen.
Fixes WEB-273
> Rename Dallas to Plano (WEB-273)

- templates/careers.hbs
Adds two email links to the talent team on the careers page. One at the end of the intro and the other below the hiring process.
Fixes WEB-274
> Add talent team email links (WEB-274)

- .travis.yml
Fixes production by setting the correct release script. Was failing because the travis.yml file had
not been updated in the scripts section to account for GIT Flow's structure.
NOTE: Must be merged via a Git Flow hotfix to merge into `master` and `develop`.
> fix(travis): production was using the wrong release script

- package-lock.json
- package.json
**Summary**
Buildit website builds will break once the dependency cache is refreshed and the broken version is downloaded.
**Detail**
[rollup-plugin-closure-compiler-js](https://github.com/camelaissani/rollup-plugin-closure-compiler-js) has a dependency on [google-closure-compiler-js](https://github.com/google/closure-compiler-js). This package is deprecated and the latest releases contain none of the code - only a deprecation message.
I've forked our dependency and pinned it's subdependency to a good known release.
**Thoughts**
We should look in to removing this dependency from our workflow - perhaps by moving to webpack.
I looked in to updating the dependency to use the new google closure compiler but its signature is quite different and I don't know if it will work well within rollup - …
> fix: use forked dependency as one of the subdependencies of `rollup-plugin-closure-compiler-js` is broken

- pages/locations/plano.md
Fixes a bug introduced by a bad merge. The Dallas studio entry on locations was recently renamed to Plano (to be more specific about where the studio actually is), but the title update got undone by accident. This fixes that.
> fix(locations): fixes Plano studio title

- package.json
Closes #199 
Eyeglass 2.2.2 and up has a bug that breaks our build. We encountered the same issue on Gravity: buildit/gravity-ui-sass#197
The fix for now is therefore to peg our dependency to the last known working version.
I have raised an issue on Eyeglass (linkedin/eyeglass#227) and, once fixed, we can update to the newer version.
> fix: pin eyeglass to 2.2.1

- .travis.yml
the current script is expanding the paths being invalidated to the folder paths of the ci server.
this fix ensures the path goes through to cloudwatch correctly
> ci(cloudfront): fixed cloudfront invalidation

- .travis.yml
Currently builds of the `next` branch are building using the `"local-dev"` environment, instead of the `"next"` environment.
This affects some of the meta tags we put in the head of the page and it also affects the google analytics environment that the site tracks against.
Please review to make sure I haven't missed any potential issues this change would make.
> ci(travis): specified 'next' environment for builds on `next` branch

- gulp/browsersync.js
- package-lock.json
- package.json
Although `npm install` will pick up the latest `next` release of Gravity, the `npm ci` that Travis CI uses won't because it goes by what's in the `package-lock.json` file. So, this PR is primarily to bump the version in there.
There were a few minor version bumps for some of our other dependencies, so I did those while I was at it.
Since the latest Gravity alpha introduces new debug CSS rules, our website pages were showing a warning due to the `<script>` tag BrowserSync injects. My second commit fixes that.
> Bumps Gravity to latest alpha release

- layouts/partials/head.njk
Some of the recently added article-specific OGP meta tags were missing the required og: prefix.
> fix: corrects the prop names for some OGP properties

- .travis.yml
The cloudfront invalidation path syntax is wrong for the `next` branch.
> ci(cloudfront invalidations): fixed `next` invalidation path

- layouts/partials/articles/list-item.njk
- layouts/partials/articles/main.njk
The image paths when using an internal (local) image do not resolve correctly. This amends them so that they resolve the same for article header and article list items.
For reference the correct image path for an article image is relative, without a starting slash. e.g. `images/articles/my-article-image.png`
> fix(images): fixed path to images for articles with local image files

- layouts/partials/articles/main.njk
The ARTICLE element had an invisible META element as its first child, with Gravity's CSS, this
causes the next element (the article's heading in this case) to have a margin top added to it.
However, in this instance it was unintentional and caused the article headings to appear slightly
lower than headings on other pages. (This was being flagged up by Gravity's debug CSS!)
This change fixes the issue by moving the META element down so that it occurs after the heading. This hasn't altered the structured meatadata in any way (I verified it in Google's structured data testing tool)
> fix: fixes layout bug on article pages

- pages/stories/5-steps-to-reducing-risk/index.html.md
- pages/stories/daily-routine/index.html.md
Avoids duplicate `<h1>` headings being created when the markdown is converted to html
> refactor(articles): change heading levels

- cypress/integration/careers.js
- templates/careers.hbs
We had a Cypress test that assumed there would always be at least one job opening on the careers page, lately that's not the case so the test has been failing (and thus failing TravisCI builds too).
I couldn't find a good solution to amend the test and Cypress own docs seem to discourage tests that are conditional
(https://docs.cypress.io/guides/core-concepts/conditional-testing.html#The-problem), so I have removed that test.
I have also added some text to appear on the careers page to inform users that there are no open job postings (otherwise it's just blank).
> fix: solves issues when there are no open job positions
